site_name: pyMut
site_description: Python library for genetic mutation visualization
site_author: pyMut Development Team
docs_dir: docs

# Repository
repo_name: Luisruimor/pyMut
repo_url: https://github.com/Luisruimor/pyMut

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github

# Include src directory in the pythonpath for the jupyter notebooks and the examples
extra:
  pythonpath:
    - src

# Plugins
plugins:
  - search
  - mkdocs-jupyter:
      # Where to find the jupyter notebooks
      jupyter_dirs:
        - 'docs/examples'
      # Execute all cells in each build
      execute: true
      # Fail the build if there are exceptions
      allow_errors: false
      # Define the kernel to use
      kernelspec: python3



# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - API Reference:
      - Core:
          - PyMutation Class: api/Core/pymutation_class.md
      - Data Loading:
          - Read MAF Files: api/Data Loading/read_maf.md
          - Read VCF Files: api/Data Loading/read_vcf.md
      - Data Export:
          - Export to MAF: api/Data Export/to_maf.md
      - Filters:
          - Genomic Range Filters: api/Filters/genomic_range.md
          - Quality Filter (PASS): api/Filters/pass_filter.md
          - Chromosome & Sample Filter: api/Filters/chrom_sample_filter.md
          - Tissue Expression Filter: api/Filters/tissue_expression_filter.md
      - Analysis Methods:
          - TMB Analysis: api/Analysis Methods/tmb_analysis.md
          - Pfam Domain Annotation: api/Analysis Methods/pfam_annotation.md
          - Known Cancer Gene Annotation: api/Analysis Methods/known_cancer_annotation.md
      - Annotation:
          - COSMIC Annotation: api/Analysis Methods/cosmic_annotation.md
          - VEP Annotation: api/Analysis Methods/vep_annotation.md
      - Visualization API:
          - Summary Plot: api/Visualization/summary_plot.md
      - Other Utilities:
          - VCF Subset Creation: api/Other Utilities/create_subset.md
          - VEP Annotation Merging: api/Other Utilities/merge_vep_annotation.md
  - Example Usage:
      - Filtering:
          - Data Filtering Examples: examples/filtering/example_filtering.ipynb
          - Tissue Expression Filter: examples/filtering/test_tissue_expression.ipynb
      - Visualization:
          - Variant Classification Plot: examples/visualization/maf_to_variant_classification.ipynb
      - Analysis:
          - TMB Analysis Demo: examples/analysis/mutation_burden_demo.ipynb
          - Pfam Domain Annotation Demo: examples/analysis/pfam_annotation_demo.ipynb
          - COSMIC Annotation Test: examples/analysis/test_cosmic_annotation.ipynb
          - Known Cancer Annotation Test: examples/analysis/test_knowncancer_simple.ipynb
      - Data Conversion:
          - VCF to PyMutation Conversion: examples/data_conversion/vcf_to_PyMutation.ipynb
          - VCF Subset Extraction: examples/data_conversion/vcf_subset_extraction.ipynb
      - Annotation:
          - VEP Annotation Merging: examples/annotation/merge_annotation.ipynb

# Copyright
copyright: Copyright &copy; 2025 pyMut Development Team
