site_name: pyMut Documentation
site_description: Python library for genetic mutation visualization
site_author: pyMut Development Team

# Repository
repo_name: your-username/pyMut
repo_url: https://github.com/your-username/pyMut

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Summary Plot: summary-plot.md

# Copyright
copyright: Copyright &copy; 2024 pyMut Development Team
