site_name: pyMut
site_description: Python library for genetic mutation visualization
site_author: pyMut Development Team
docs_dir: docs

# Repository
repo_name: Luisruimor/pyMut
repo_url: https://github.com/Luisruimor/pyMut

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github

# Include src directory in the pythonpath for the jupyter notebooks and the examples
extra:
  pythonpath:
    - src

# Plugins
plugins:
  - search
  - mkdocs-jupyter:
      # Where to find the jupyter notebooks
      jupyter_dirs:
        - 'docs/examples'
      # Execute all cells in each build
      execute: false
      # Fail the build if there are exceptions
      allow_errors: false
      # Define the kernel to use
      kernelspec: python3



# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - API Reference:
      - Core:
          - PyMutation Class: api/Core/pymutation_class.md
      - Data Loading:
          - Read MAF Files: api/Data Loading/read_maf.md
          - Read VCF Files: api/Data Loading/read_vcf.md
      - Data Export:
          - Export to MAF: api/Data Export/to_maf.md
          - Export to VCF: api/Data Export/to_vcf.md
      - Data Combination: api/Data Combination/combine_data.md
      - Filters:
          - Genomic Range Filters: api/Filters/genomic_range.md
          - Quality Filter (PASS): api/Filters/pass_filter.md
          - Chromosome & Sample Filter: api/Filters/chrom_sample_filter.md
          - Tissue Expression Filter: api/Filters/tissue_expression_filter.md
      - Analysis Methods:
          - TMB Analysis: api/Analysis Methods/tmb_analysis.md
          - Pfam Domains Annotation: api/Analysis Methods/pfam_domains.md
          - Mutational Signatures: api/Analysis Methods/mutational_signatures.md
      - Annotation:
          - Known Cancer Gene Annotation: api/Analysis Methods/known_cancer_annotation.md
          - VEP Annotation: api/Analysis Methods/vep_annotation.md
          - PFAM Annotation: api/Analysis Methods/pfam_annotation.md
          - Actionable Mutation Annotation: api/Analysis Methods/actionable_mutation_annotation.md
      - Visualization API:
          - Summary Plot: api/Visualization/summary_plot.md

  - Example Usage:
      - Input Data:
          - VCF: examples/data/input_read_vcf.ipynb
          - MAF: examples/data/input_read_maf.ipynb
      - Output Data:
          - VCF: examples/data/vcf_to_maf_and_vcf.ipynb
          - MAF: examples/data/maf_to_vcf_and_maf.ipynb
      - Combination: examples/data/combination_2maf.ipynb
      - Filtering:
          - Data Filtering Examples: examples/filtering/example_filtering.ipynb
          - Tissue Expression Filter: examples/filtering/tissue_expression.ipynb
      - Annotation:
          - VEP Annotation: examples/annotation/vep_annotation.ipynb
          - Known Cancer: examples/annotation/cosmic_cancer_annotation.ipynb
          - Actionable Mutation: examples/annotation/actionable_mutation_annotation.ipynb
      - Analysis:
          - TMB Analysis: examples/analysis/mutation_burden.ipynb
          - Mutational Signatures: examples/analysis/mutational_signatures.ipynb
          - PFAM Domains: examples/analysis/domains_pfam.ipynb
      - Visualization (beta):
          - Variant Classification Plot: examples/visualization/maf_to_variant_classification.ipynb
          - Oncoplot Example: examples/visualization/oncoplot_example.ipynb
          - Summary Plot Example: examples/visualization/summary_plot_example.ipynb
# Copyright
copyright: Copyright &copy; 2025 pyMut Development Team
