site_name: pyMut
site_description: Python library for genetic mutation visualization
site_author: pyMut Development Team
docs_dir: docs

# Repository
repo_name: Luisruimor/pyMut
repo_url: https://github.com/Luisruimor/pyMut

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - mkdocs-jupyter:
      jupyter_dirs: ['docs/examples']



# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - API Reference:
      - Core:
          - PyMutation Class: api/Core/pymutation_class.md
      - Data Loading:
          - Read MAF Files: api/Data Loading/read_maf.md
          - Read VCF Files: api/Data Loading/read_vcf.md
      - Data Export:
          - Export to MAF: api/Data Export/to_maf.md
      - Filters:
          - Genomic Range Filters: api/Filters/genomic_range.md
          - Quality Filter (PASS): api/Filters/pass_filter.md
          - Chromosome & Sample Filter: api/Filters/chrom_sample_filter.md
      - Analysis Methods:
          - TMB Analysis: api/Analysis Methods/tmb_analysis.md
          - Pfam Domain Annotation: api/Analysis Methods/pfam_annotation.md
      - Visualization API:
          - Summary Plot: api/Visualization/summary_plot.md
      - Other Utilities:
          - VCF Subset Creation: api/Other Utilities/create_subset.md
          - VEP Annotation Merging: api/Other Utilities/merge_vep_annotation.md
  - Example Usage:
      - Variant Classification Plot: examples/maf_to_variant_classification.ipynb
      - Data Filtering Examples: examples/example_filtering.ipynb
      - TMB Analysis Demo: examples/mutation_burden_demo.ipynb
      - Pfam Domain Annotation Demo: examples/pfam_annotation_demo.ipynb
      - VEP Annotation Merging: examples/merge_annotation.ipynb
      - VCF Subset Extraction: examples/vcf_subset_extraction.ipynb
      - VCF to PyMutation Conversion: examples/vcf_to_PyMutation.ipynb

# Copyright
copyright: Copyright &copy; 2024 pyMut Development Team
